version: '3.3'

services:

  db:
    image: mysql:5.6
    ports:
      - "6033:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: 123
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123


  adminer:
    image: adminer
    ports:
      - "8080:8080"